/********************************************************************
* DopingDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DopingDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDopingDict();
extern void G__cpp_setup_inheritanceDopingDict();
extern void G__cpp_setup_typetableDopingDict();
extern void G__cpp_setup_memvarDopingDict();
extern void G__cpp_setup_globalDopingDict();
extern void G__cpp_setup_memfuncDopingDict();
extern void G__cpp_setup_funcDopingDict();
extern void G__set_cpp_environmentDopingDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Doping.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DopingDictLN_TClass;
extern G__linked_taginfo G__DopingDictLN_TBuffer;
extern G__linked_taginfo G__DopingDictLN_TMemberInspector;
extern G__linked_taginfo G__DopingDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DopingDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DopingDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DopingDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DopingDictLN_Doping;

/* STUB derived class for protected member access */
