/********************************************************************
* electronDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error electronDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableelectronDict();
extern void G__cpp_setup_inheritanceelectronDict();
extern void G__cpp_setup_typetableelectronDict();
extern void G__cpp_setup_memvarelectronDict();
extern void G__cpp_setup_globalelectronDict();
extern void G__cpp_setup_memfuncelectronDict();
extern void G__cpp_setup_funcelectronDict();
extern void G__set_cpp_environmentelectronDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "electron.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__electronDictLN_TClass;
extern G__linked_taginfo G__electronDictLN_TBuffer;
extern G__linked_taginfo G__electronDictLN_TMemberInspector;
extern G__linked_taginfo G__electronDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__electronDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__electronDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__electronDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__electronDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__electronDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR;
extern G__linked_taginfo G__electronDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__electronDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__electronDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__electronDictLN_electron;
extern G__linked_taginfo G__electronDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR;
extern G__linked_taginfo G__electronDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
