/********************************************************************
* PartIncidenceDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PartIncidenceDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePartIncidenceDict();
extern void G__cpp_setup_inheritancePartIncidenceDict();
extern void G__cpp_setup_typetablePartIncidenceDict();
extern void G__cpp_setup_memvarPartIncidenceDict();
extern void G__cpp_setup_globalPartIncidenceDict();
extern void G__cpp_setup_memfuncPartIncidenceDict();
extern void G__cpp_setup_funcPartIncidenceDict();
extern void G__set_cpp_environmentPartIncidenceDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PartIncidence.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PartIncidenceDictLN_TClass;
extern G__linked_taginfo G__PartIncidenceDictLN_TBuffer;
extern G__linked_taginfo G__PartIncidenceDictLN_TMemberInspector;
extern G__linked_taginfo G__PartIncidenceDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PartIncidenceDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PartIncidenceDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PartIncidenceDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PartIncidenceDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PartIncidenceDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PartIncidenceDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PartIncidenceDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PartIncidenceDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PartIncidenceDictLN_PartIncidence;
extern G__linked_taginfo G__PartIncidenceDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__PartIncidenceDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
