/********************************************************************
* YTransportDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error YTransportDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableYTransportDict();
extern void G__cpp_setup_inheritanceYTransportDict();
extern void G__cpp_setup_typetableYTransportDict();
extern void G__cpp_setup_memvarYTransportDict();
extern void G__cpp_setup_globalYTransportDict();
extern void G__cpp_setup_memfuncYTransportDict();
extern void G__cpp_setup_funcYTransportDict();
extern void G__set_cpp_environmentYTransportDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "YTransport.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__YTransportDictLN_TClass;
extern G__linked_taginfo G__YTransportDictLN_TBuffer;
extern G__linked_taginfo G__YTransportDictLN_TMemberInspector;
extern G__linked_taginfo G__YTransportDictLN_string;
extern G__linked_taginfo G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__YTransportDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__YTransportDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR;
extern G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__YTransportDictLN_YGeometry;
extern G__linked_taginfo G__YTransportDictLN_Damage;
extern G__linked_taginfo G__YTransportDictLN_YPartIncidence;
extern G__linked_taginfo G__YTransportDictLN_YTransport;
extern G__linked_taginfo G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR;
extern G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
