//
// File generated by rootcint at Thu Nov 16 20:10:20 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME YTransportDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "YTransportDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void YTransport_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_YTransport(void *p = 0);
   static void *newArray_YTransport(Long_t size, void *p);
   static void delete_YTransport(void *p);
   static void deleteArray_YTransport(void *p);
   static void destruct_YTransport(void *p);
   static void streamer_YTransport(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::YTransport*)
   {
      ::YTransport *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::YTransport >(0);
      static ::ROOT::TGenericClassInfo 
         instance("YTransport", ::YTransport::Class_Version(), "./YTransport.h", 36,
                  typeid(::YTransport), ::ROOT::DefineBehavior(ptr, ptr),
                  &::YTransport::Dictionary, isa_proxy, 0,
                  sizeof(::YTransport) );
      instance.SetNew(&new_YTransport);
      instance.SetNewArray(&newArray_YTransport);
      instance.SetDelete(&delete_YTransport);
      instance.SetDeleteArray(&deleteArray_YTransport);
      instance.SetDestructor(&destruct_YTransport);
      instance.SetStreamerFunc(&streamer_YTransport);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::YTransport*)
   {
      return GenerateInitInstanceLocal((::YTransport*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::YTransport*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr YTransport::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *YTransport::Class_Name()
{
   return "YTransport";
}

//______________________________________________________________________________
const char *YTransport::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::YTransport*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int YTransport::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::YTransport*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void YTransport::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::YTransport*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *YTransport::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::YTransport*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void YTransport::Streamer(TBuffer &R__b)
{
   // Stream an object of class YTransport.

   ::Error("YTransport::Streamer", "version id <=0 in ClassDef, dummy Streamer() called"); if (R__b.IsReading()) { }
}

//______________________________________________________________________________
void YTransport::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class YTransport.
      TClass *R__cl = ::YTransport::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*beam", &beam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Efield", (void*)&Efield);
      R__insp.InspectMember("vector<E_field>", (void*)&Efield, "Efield.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "elist", (void*)&elist);
      R__insp.InspectMember("vector<electron>", (void*)&elist, "elist.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cube", &cube);
      R__insp.InspectMember(cube, "cube.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Zdebug", &Zdebug);
      R__insp.InspectMember(Zdebug, "Zdebug.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "partgen", &partgen);
      R__insp.InspectMember(partgen, "partgen.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pm3d[100]", pm3d);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*htime", &htime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hvd", &hvd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hvth", &hvth);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_YTransport(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::YTransport : new ::YTransport;
   }
   static void *newArray_YTransport(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::YTransport[nElements] : new ::YTransport[nElements];
   }
   // Wrapper around operator delete
   static void delete_YTransport(void *p) {
      delete ((::YTransport*)p);
   }
   static void deleteArray_YTransport(void *p) {
      delete [] ((::YTransport*)p);
   }
   static void destruct_YTransport(void *p) {
      typedef ::YTransport current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_YTransport(TBuffer &buf, void *obj) {
      ((::YTransport*)obj)->::YTransport::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::YTransport

/********************************************************
* YTransportDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableYTransportDict();

extern "C" void G__set_cpp_environmentYTransportDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("YTransport.h");
  G__cpp_reset_tagtableYTransportDict();
}
#include <new>
extern "C" int G__cpp_dllrevYTransportDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* YTransport */
static int G__YTransportDict_316_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   YTransport* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new YTransport[n];
     } else {
       p = new((void*) gvp) YTransport[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new YTransport;
     } else {
       p = new((void*) gvp) YTransport;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__YTransportDictLN_YTransport));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) YTransport::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) YTransport::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) YTransport::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      YTransport::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const YTransport*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) YTransport::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) YTransport::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) YTransport::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) YTransport::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->initialize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->transport();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->event((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->save(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->load(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__YTransportDict_316_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((YTransport*) G__getstructoffset())->debug();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__YTransportDict_316_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   YTransport* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new YTransport(*(YTransport*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__YTransportDictLN_YTransport));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef YTransport G__TYTransport;
static int G__YTransportDict_316_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (YTransport*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((YTransport*) (soff+(sizeof(YTransport)*i)))->~G__TYTransport();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (YTransport*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((YTransport*) (soff))->~G__TYTransport();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* YTransport */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncYTransportDict {
 public:
  G__Sizep2memfuncYTransportDict(): p(&G__Sizep2memfuncYTransportDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncYTransportDict::*p)();
};

size_t G__get_sizep2memfuncYTransportDict()
{
  G__Sizep2memfuncYTransportDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceYTransportDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableYTransportDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__YTransportDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__YTransportDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<E_field>",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__YTransportDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__YTransportDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<electron>",117,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* YTransport */
static void G__setup_memvarYTransport(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__YTransportDictLN_YTransport));
   { YTransport *p; p=(YTransport*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beam)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__YTransportDictLN_PartIncidence),-1,-1,1,"beam=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Efield)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR),G__defined_typename("vector<E_field>"),-1,1,"Efield=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->elist)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR),G__defined_typename("vector<electron>"),-1,1,"elist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cube)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TPolyLine3D),-1,-1,1,"cube=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Zdebug)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TGraph),-1,-1,1,"Zdebug=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->partgen)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TPolyMarker3D),-1,-1,1,"partgen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pm3d)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TPolyMarker3D),-1,-1,1,"pm3d[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->htime)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TH1D),-1,-1,1,"htime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hvd)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TH1D),-1,-1,1,"hvd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hvth)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__YTransportDictLN_TH1D),-1,-1,1,"hvth=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarYTransportDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncYTransport(void) {
   /* YTransport */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__YTransportDictLN_YTransport));
   G__memfunc_setup("YTransport",1062,G__YTransportDict_316_0_1, 105, G__get_linked_tagnum(&G__YTransportDictLN_YTransport), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__YTransportDict_316_0_2, 85, G__get_linked_tagnum(&G__YTransportDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&YTransport::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__YTransportDict_316_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&YTransport::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__YTransportDict_316_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&YTransport::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__YTransportDict_316_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&YTransport::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__YTransportDict_316_0_6, 85, G__get_linked_tagnum(&G__YTransportDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__YTransportDict_316_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__YTransportDict_316_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__YTransportDict_316_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__YTransportDict_316_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&YTransport::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__YTransportDict_316_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&YTransport::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__YTransportDict_316_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&YTransport::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__YTransportDict_316_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&YTransport::DeclFileLine) ), 0);
   G__memfunc_setup("initialize",1074,G__YTransportDict_316_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("transport",1005,G__YTransportDict_316_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("event",546,G__YTransportDict_316_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("print",557,G__YTransportDict_316_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("save",431,G__YTransportDict_316_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("load",416,G__YTransportDict_316_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("debug",519,G__YTransportDict_316_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("YTransport", 1062, G__YTransportDict_316_0_21, (int) ('i'), G__get_linked_tagnum(&G__YTransportDictLN_YTransport), -1, 0, 1, 1, 1, 0, "u 'YTransport' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~YTransport", 1188, G__YTransportDict_316_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncYTransportDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalYTransportDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcYTransportDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__YTransportDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__YTransportDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TPolyLine3D = { "TPolyLine3D" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TPolyMarker3D = { "TPolyMarker3D" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR = { "vector<E_field,allocator<E_field> >" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<E_field,allocator<E_field> >::iterator>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_PartIncidence = { "PartIncidence" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_YTransport = { "YTransport" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR = { "vector<electron,allocator<electron> >" , 99 , -1 };
G__linked_taginfo G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<electron,allocator<electron> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableYTransportDict() {
  G__YTransportDictLN_TClass.tagnum = -1 ;
  G__YTransportDictLN_TBuffer.tagnum = -1 ;
  G__YTransportDictLN_TMemberInspector.tagnum = -1 ;
  G__YTransportDictLN_string.tagnum = -1 ;
  G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__YTransportDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__YTransportDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__YTransportDictLN_TH1D.tagnum = -1 ;
  G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__YTransportDictLN_TGraph.tagnum = -1 ;
  G__YTransportDictLN_TPolyLine3D.tagnum = -1 ;
  G__YTransportDictLN_TPolyMarker3D.tagnum = -1 ;
  G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR.tagnum = -1 ;
  G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__YTransportDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__YTransportDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__YTransportDictLN_PartIncidence.tagnum = -1 ;
  G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__YTransportDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__YTransportDictLN_YTransport.tagnum = -1 ;
  G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR.tagnum = -1 ;
  G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableYTransportDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_string);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TPolyLine3D);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TPolyMarker3D);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_vectorlEE_fieldcOallocatorlEE_fieldgRsPgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_reverse_iteratorlEvectorlEE_fieldcOallocatorlEE_fieldgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_PartIncidence);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__YTransportDictLN_YTransport),sizeof(YTransport),-1,1280,(char*)NULL,G__setup_memvarYTransport,G__setup_memfuncYTransport);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_vectorlEelectroncOallocatorlEelectrongRsPgR);
   G__get_linked_tagnum_fwd(&G__YTransportDictLN_reverse_iteratorlEvectorlEelectroncOallocatorlEelectrongRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupYTransportDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupYTransportDict()");
  G__set_cpp_environmentYTransportDict();
  G__cpp_setup_tagtableYTransportDict();

  G__cpp_setup_inheritanceYTransportDict();

  G__cpp_setup_typetableYTransportDict();

  G__cpp_setup_memvarYTransportDict();

  G__cpp_setup_memfuncYTransportDict();
  G__cpp_setup_globalYTransportDict();
  G__cpp_setup_funcYTransportDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncYTransportDict();
  return;
}
class G__cpp_setup_initYTransportDict {
  public:
    G__cpp_setup_initYTransportDict() { G__add_setup_func("YTransportDict",(G__incsetup)(&G__cpp_setupYTransportDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initYTransportDict() { G__remove_setup_func("YTransportDict"); }
};
G__cpp_setup_initYTransportDict G__cpp_setup_initializerYTransportDict;

